Add Describe permission to EMR
DuckbillGroup/onboarding pull request #16
Opened 2020-11-23 18:49 UTC by petecheslock

2020-11-23 21:38 UTC, jcderose commented
As long as you have `elasticmapreduce:List*` access already, this looks good to me.

2020-11-25 01:10 UTC, jcderose requested changes
Looks like the `Configuration` action is singular, not plural.

Also, I don't see `s3:ListStorageLensConfigurations` in the ViewOnlyAccess policy so you may need to add that as well.

2020-11-25 01:10 UTC, jcderose commented on aws-cli/resource-discovery-policy.json
> +                "s3:ListStorageLensConfigurations",
```suggestion
                "s3:ListStorageLensConfiguration",
```

2020-11-25 01:10 UTC, jcderose commented on cloudformation/duckbill-iam-role.yml
> +              - 's3:ListStorageLensConfigurations'
```suggestion
              - 's3:ListStorageLensConfiguration'
```

2020-11-25 01:10 UTC, jcderose commented on terraform/duckbill-iam-role.tf
> +      "s3:ListStorageLensConfigurations",
```suggestion
      "s3:ListStorageLensConfiguration",
```

2020-11-25 14:48 UTC, petecheslock commented
Looking at the role it looks like the "list" permission is plural.  
![Screen Shot 2020-11-25 at 9 46 14 AM](https://user-images.githubusercontent.com/511733/100242958-5e64be00-2f03-11eb-9c98-8cda1bdd96a9.png)

2020-11-25 15:42 UTC, jcderose commented
Blarg, I was looking at the wrong thing. I thought I was making a change to `s3:GetStorageLensConfiguration`, not `s3:ListStorageLensConfigurations`. 🤦

2020-11-25 15:43 UTC, jcderose approved these changes
Blarg, I was looking at the wrong thing. I thought I was making a change to `s3:GetStorageLensConfiguration`, not `s3:ListStorageLensConfigurations`. 🤦

2020-11-25 15:43 UTC, merged